DROP DATABASE IF EXISTS GIT_TEST;
DROP DATABASE IF EXISTS GIT_TEST2;
DROP DATABASE IF EXISTS GIT_TEST3;
DROP DATABASE IF EXISTS GIT_TEST4;
DROP DATABASE IF EXISTS GIT_TEST5;
DROP DATABASE IF EXISTS GIT_TEST6;
DROP DATABASE IF EXISTS GIT_TEST7;
